// Generated by ts-to-zod
import { z } from 'zod';

export const bloodPressureDTOSchema = z.object({
  systolic: z.number(),
  diastolic: z.number(),
});

export const illnessDTOSchema = z.object({
  case: z.string(),
  category: z.string(),
  age: z.number(),
  year: z.number(),
  notes: z.string().optional(),
});

export const surgeryDTOSchema = z.object({
  year: z.number(),
  case: z.string(),
});

export const medicationIntakePeriodDTOSchema = z.object({
  start: z.string(),
  end: z.string().optional(),
});

export const medicationDTOSchema = z.object({
  name: z.string(),
  cause: z.string(),
  period: medicationIntakePeriodDTOSchema,
});

export const relativeDTOSchema = z.object({
  id: z.string(),
  name: z.string(),
  value: z.string(),
  order: z.number().optional(),
});

export const allergiesDTOSchema = z.object({
  household: z.array(z.string()),
  drug: z.array(z.string()),
});

export const badHabitsDTOSchema = z.object({
  alcohol: z.boolean(),
  smoking: z.boolean(),
});

export const familyHistoryRecordDTOSchema = z.object({
  relative: relativeDTOSchema,
  case: z.string(),
  category: z.string(),
  notes: z.string(),
});

export const patientDTOSchema = z.object({
  name: z.string(),
  birthDate: z.string(),
  height: z.number(),
  weight: z.number(),
  bloodPressure: bloodPressureDTOSchema,
  illness: z.array(illnessDTOSchema),
  surgeries: z.array(surgeryDTOSchema),
  medications: z.array(medicationDTOSchema),
  familyHistory: z.array(familyHistoryRecordDTOSchema),
  allergies: allergiesDTOSchema,
  badHabits: badHabitsDTOSchema,
  email: z.string(),
  password: z.string(),
});
