// Generated by ts-to-zod
import { z } from 'zod';

export const bloodPressureDTOSchema = z.object({
  systolic: z.number(),
  diastolic: z.number(),
});

export const illnessDTOSchema = z.object({
  case: z.string(),
  category: z.string(),
  age: z.number(),
  year: z.number(),
  notes: z.string().optional(),
});

export const operationDTOSchema = z.object({
  year: z.number(),
  case: z.string(),
});

export const medicationIntakePeriodDTOSchema = z.object({
  start: z.string(),
  end: z.string().optional(),
});

export const medicationDTOSchema = z.object({
  name: z.string(),
  cause: z.string(),
  periods: z.array(medicationIntakePeriodDTOSchema),
});

export const familyHistoryRecordDTOSchema = z.object({
  person: z.string(),
  case: z.string(),
  category: z.string(),
  notes: z.string(),
});

export const allergiesDTOSchema = z.object({
  household: z.array(z.string()),
  drug: z.array(z.string()),
});

export const badHabitsDTOSchema = z.object({
  alcohol: z.boolean(),
  smoking: z.boolean(),
});

export const patientDTOSchema = z.object({
  name: z.string(),
  birthDate: z.string(),
  height: z.number(),
  weight: z.number(),
  bloodPressure: bloodPressureDTOSchema,
  illness: z.array(illnessDTOSchema),
  operations: z.array(operationDTOSchema),
  medications: z.array(medicationDTOSchema),
  familyHistory: z.array(familyHistoryRecordDTOSchema),
  allergies: allergiesDTOSchema,
  badHabits: badHabitsDTOSchema,
  email: z.string(),
  password: z.string(),
});
